# Scalar, Vector, Matrix

## import libraries

In [1]:
import numpy as np

## Scalar

In [2]:
s = 5

In [3]:
s

5

## Vector

In [4]:
v = np.array([5,-2,4])

In [5]:
v

array([ 5, -2,  4])

## Matrix

In [6]:
m = np.array([[5,12,6],[-3,0,14]])

In [7]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

## Tensors

In [19]:
m1 = np.array([[1,2,3],[7,6,5]])

In [22]:
m2 = np.array([[-1,3,0],[2,3,100]])

In [24]:
t = np.array([m1,m2])

In [25]:
t

array([[[  1,   2,   3],
        [  7,   6,   5]],

       [[ -1,   3,   0],
        [  2,   3, 100]]])

In [26]:
t.shape
# (2, 2, 3)
# artinya -> 2 matrix dengan ukuran 2 x 3

(2, 2, 3)

## Data Types

In [8]:
type(s)

int

In [9]:
type(v)

numpy.ndarray

In [10]:
type(m)

numpy.ndarray

ndarray = n-dimensional array

In [11]:
s_arr = np.array(5)

In [12]:
s_arr

array(5)

In [13]:
type(s_arr)

numpy.ndarray

## Data Shape

In [16]:
v.shape

(3,)

In [17]:
m.shape

(2, 3)

## Operational Matrices

### Addition

In [27]:
m_add = m1 + m2
m_add

array([[  0,   5,   3],
       [  9,   9, 105]])

## Substraction

In [28]:
m_sub = m1 - m2
m_sub

array([[  2,  -1,   3],
       [  5,   3, -95]])