In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
import seaborn as sns

data = pd.read_csv('1.02.+Multiple+linear+regression.csv')
data.head()


/Users/gabrielmarcellinojoestiawan/opt/anaconda3/lib/python3.9/site-packages/scipy/__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.0
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


SAT   GPA  Rand 1,2,3
0  1714  2.40           1
1  1664  2.52           3
2  1760  2.54           3
3  1685  2.74           3
4  1693  2.83           2

Note : <br>
- <strong> sample  is the machine learning word for observation<strong><br>

In [3]:
data.describe()

SAT        GPA  Rand 1,2,3
count    84.000000  84.000000   84.000000
mean   1845.273810   3.330238    2.059524
std     104.530661   0.271617    0.855192
min    1634.000000   2.400000    1.000000
25%    1772.000000   3.190000    1.000000
50%    1846.000000   3.380000    2.000000
75%    1934.000000   3.502500    3.000000
max    2050.000000   3.810000    3.000000

In [4]:
x = data[['SAT','Rand 1,2,3']]
y = data['GPA']

Regression

In [5]:
reg = LinearRegression()
reg.fit(x,y)

LinearRegression()

In [6]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [7]:
reg.intercept_

0.29603261264909486

Calculating R-Squared

In [8]:
reg.score(x,y)

0.40668119528142843

### Adjusted R-Squared Formula (R^2)

$R^2_{adj.} = 1 - (1-R^2) * \frac{n-1}{n-p-1}$ <br>

n = the number of observations <br>
p = the number of predictors


In [9]:
print("n (observation) = 84 , p (independant variable) = 2")
x.shape

n (observation) = 84 , p (independant variable) = 2


(84, 2)

In [10]:
rsq = reg.score(x,y)
n = x.shape[0]
p = x.shape[1]
radj = 1 - (1 - (rsq)) * ((n - 1)/(n - p - 1))
radj

0.39203134825134023

$R^2.{adj} < R^2$ = one or more the predictors have little or no explanatory power

### Feature Selection with F-Regression

Note : <br>
- feature selection simplifies models <br>
- if variable has a p-value > 0.05, we can disregard it <br>
- note that for a simple linear regerssion, the p-value of F-stat = the p-value of the only independent variable <br>

In [11]:
from sklearn.feature_selection import f_regression

In [12]:
f_regression(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

left : F - Statistics <br>
right : p - Values <br>

In [13]:
p_val = f_regression(x,y)[1]
p_val.round(3) 
#this is array  x = data[['SAT','Rand 1,2,3']]

array([0.   , 0.676])

### Creating Summary Table 

In [14]:
reg_summary = pd.DataFrame(data=x.columns ,columns=['features'])
reg_summary

features
0         SAT
1  Rand 1,2,3

In [15]:
reg_summary['Coefficients'] = reg.coef_
reg_summary['p - values'] = p_val.round(3)

In [16]:
reg_summary

features  Coefficients  p - values
0         SAT      0.001654       0.000
1  Rand 1,2,3     -0.008270       0.676

### Feature Scalling

In [17]:
from sklearn.preprocessing import StandardScaler

In [18]:
scaler = StandardScaler()

In [19]:
scaler.fit(x)

StandardScaler()

In [20]:
x_scaled = scaler.transform(x)
x_scaled

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,

### Feature Scalling

In [23]:
reg = LinearRegression()
reg.fit(x_scaled,y)

LinearRegression()

In [24]:
reg.coef_

array([ 0.17181389, -0.00703007])

In [25]:
reg.intercept_

3.330238095238095

In [27]:
reg_summary = pd.DataFrame(data=[['Bias'],['SAT'],['Rand 1,2,3']] ,columns=['features'])
reg_summary['Weights'] = reg.intercept_,reg.coef_[0],reg.coef_[1]


In [28]:
reg_summary

features   Weights
0   Intercept  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030

Weights is 'machine learning' word for coefficients <br>
'machine learning' word for intercept is bias

### Making Predictions with feature scalling

In [34]:
new_data = pd.DataFrame(data=[[1890,1],[1678,3]],columns=['SAT','Rand 1,2,3'])
new_data

SAT  Rand 1,2,3
0  1890           1
1  1678           3

In [35]:
new_data_scaled = scaler.transform(new_data)
new_data_scaled

array([[ 0.43044613, -1.24637147],
       [-1.60984791,  1.10632974]])

In [36]:
reg.predict(new_data_scaled)

array([3.41295679, 3.04586629])

#### Removed Rand 1,2,3

In [39]:
reg_new = LinearRegression()
x_new_matrix = x_scaled[:,0].reshape(-1,1)
reg_new.fit(x_new_matrix,y)

LinearRegression()

In [41]:
reg_new.predict(new_data_scaled[:,0].reshape(-1,1))

array([3.40429071, 3.05328485])