# TRAIN TEST SPLIT

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split


In [32]:
a = np.arange(1,101)
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [31]:
b = np.arange(401,501)
b

array([401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413,
       414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426,
       427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439,
       440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452,
       453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465,
       466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478,
       479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491,
       492, 493, 494, 495, 496, 497, 498, 499, 500])

In [33]:
#split for data frame
def split_train_test(data, test_ratio):
 shuffled_indices = np.random.permutation(len(data))
 test_set_size = int(len(data) * test_ratio)
 test_indices = shuffled_indices[:test_set_size]
 train_indices = shuffled_indices[test_set_size:]
 return data.iloc[train_indices], data.iloc[test_indices]

a_train,a_test,b_train,b_test = train_test_split(a,b,test_size=0.2,random_state=42)

In [34]:
a_train.shape,a_test.shape

((80,), (20,))

In [35]:
a_train

array([ 56,  89,  27,  43,  70,  16,  41,  97,  10,  73,  12,  48,  86,
        29,  94,   6,  67,  66,  36,  17,  50,  35,   8,  96,  28,  20,
        82,  26,  63,  14,  25,   4,  18,  39,   9,  79,   7,  65,  37,
        90,  57, 100,  55,  44,  51,  68,  47,  69,  62,  98,  80,  42,
        59,  49,  99,  58,  76,  33,  95,  60,  64,  85,  38,  30,   2,
        53,  22,   3,  24,  88,  92,  75,  87,  83,  21,  61,  72,  15,
        93,  52])

In [36]:
a_test

array([84, 54, 71, 46, 45, 40, 23, 81, 11,  1, 19, 31, 74, 34, 91,  5, 77,
       78, 13, 32])

In [37]:
b_train.shape,b_test.shape

((80,), (20,))

In [38]:
b_train

array([456, 489, 427, 443, 470, 416, 441, 497, 410, 473, 412, 448, 486,
       429, 494, 406, 467, 466, 436, 417, 450, 435, 408, 496, 428, 420,
       482, 426, 463, 414, 425, 404, 418, 439, 409, 479, 407, 465, 437,
       490, 457, 500, 455, 444, 451, 468, 447, 469, 462, 498, 480, 442,
       459, 449, 499, 458, 476, 433, 495, 460, 464, 485, 438, 430, 402,
       453, 422, 403, 424, 488, 492, 475, 487, 483, 421, 461, 472, 415,
       493, 452])

In [39]:
b_test

array([484, 454, 471, 446, 445, 440, 423, 481, 411, 401, 419, 431, 474,
       434, 491, 405, 477, 478, 413, 432])